export const mockData = [
    {
        id: 1,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "14,339,814",
    area: 206,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",

    isFavorite: false,
    },
    {
        id: 2,
    title: "فيلا فاخرة في حي النخيل",   
    subtitle: "حي النخيل - جدة",     
    image: "/main-page/areas/riyad.png",      
    badge: "مميزة",
    price: "14,339,814",
    area: 206,  
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "شركة الأفق العقارية",     
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
{
        id: 3,  
    title: "شقة فاخرة بإطلالة بحرية",   
    subtitle: "كورنيش جدة - جدة",
    image: "/main-page/areas/city.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 120,
    bedrooms: 2,    
    bathrooms: 2,
    floors: 1,
    },
    {
        id: 4,  
    title: "فيلا حديثة في حي الحمراء",   
    subtitle: "حي الحمراء - جدة",     
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 180,  
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
},

];

export const mockData2 = [
    {
        id: 1,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "14,339,814",
    area: 206,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",

    isFavorite: false,
    },
    {
        id: 2,
    title: "فيلا فاخرة في حي النخيل",   
    subtitle: "حي النخيل - جدة",     
    image: "/main-page/areas/riyad.png",      
    badge: "مميزة",
    price: "14,339,814",
    area: 206,  
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "شركة الأفق العقارية",     
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
{
        id: 3,  
    title: "شقة فاخرة بإطلالة بحرية",   
    subtitle: "كورنيش جدة - جدة",
    image: "/main-page/areas/city.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 120,
    bedrooms: 2,    
    bathrooms: 2,
    floors: 1,
    },
    {
        id: 4,  
    title: "فيلا حديثة في حي الحمراء",   
    subtitle: "حي الحمراء - جدة",     
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 180,  
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
},

];