export const mockData = [
    {
        id: 1,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "14,339,814",
    area: 206,
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",

    isFavorite: false,
    },
    {
        id: 2,
    title: "فيلا فاخرة في حي النخيل",   
    subtitle: "حي النخيل - جدة",     
    image: "/main-page/areas/riyad.png",      
    badge: "مميزة",
    price: "14,339,814",
    area: 206,  
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "شركة الأفق العقارية",     
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
{
        id: 3,  
    title: "شقة فاخرة بإطلالة بحرية",   
    subtitle: "كورنيش جدة - جدة",
    image: "/main-page/areas/city.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 120,
    bedrooms: 2,    
    bathrooms: 2,
    floors: 1,
    company: "العقارية المتحدة",
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",

    isFavorite: false,
    },
    {
        id: 4,  
    title: "فيلا حديثة في حي الحمراء",   
    subtitle: "حي الحمراء - جدة",     
    image: "/main-page/areas/riyyad.png",
    badge: "مميزة",
    price: "8,500,000",
    area: 180,  
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    company: "شركة الأفق العقارية",
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    
},
{
        id: 5,  
    title: "شقة فاخرة في وسط المدينة",   
    subtitle: "المدينة المنورة - المدينة",
    image: "/main-page/areas/damam.png",

    badge: "مميزة",
    price: "7,200,000",
    area: 150,
    bedrooms: 3,    
    bathrooms: 2,
    floors: 1,
    company: "العقارية المتحدة",
 companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,   
},{
        id: 6,  
    title: "منزل عائلي واسع مع حديقة",   
    subtitle: "حي الورود - مكة",     
   image: "/main-page/areas/riyad.png",
    badge: "مميزة",
    price: "12,750,000",    
    area: 250,  
    bedrooms: 5,
    bathrooms: 3,    
    floors: 2,
    company: "شركة الأفق العقارية",
 companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
}

];
export const mockData2 = [
    {
        id: 5,
    title: "شقة حديثة في وسط المدينة",
    subtitle: "منطقة البنوك - الرياض",
   image: "/main-page/areas/damam.png",
    badge: "مميزة",
    price: "10,500,000",
    area: 150,
    bedrooms: 3,    
    bathrooms: 2,
    floors: 1,
    company: "العقارية المتحدة",
 companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
    {
        id: 6,  
    title: "منزل عائلي واسع مع حديقة",   
    subtitle: "حي الورود - مكة",     
   image: "/main-page/areas/riyad.png",
    badge: "مميزة",
    price: "12,750,000",
    area: 250,  
    bedrooms: 5,
    bathrooms: 3,
    floors: 2,
    company: "شركة الأفق العقارية",     
 companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
    {
        id: 7,  
    title: "فيلا فاخرة بإطلالة بحرية",   
    subtitle: "كورنيش جدة - جدة",
   image: "/main-page/areas/damam.png",
    badge: "مميزة",
    price: "20,000,000",
    area: 300,
    bedrooms: 4,    
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    },
    {
        id: 8,  
    title: "شقة أنيقة في حي الروضة",   
    subtitle: "حي الروضة - مكة",     
   image: "/main-page/areas/riyad.png",
    badge: "مميزة",
    price: "9,200,000",
    area: 130,  
    bedrooms: 2,
    bathrooms: 1,
    floors: 1,
    company: "شركة الأفق العقارية",     
 companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,

    },
    {
        id: 9,  
    title: "منزل ريفي هادئ مع حديقة",   
    subtitle: "الدرعية - الرياض",
   image: "/main-page/areas/damam.png",
    badge: "مميزة",
    price: "11,300,000",
    area: 220,  
    bedrooms: 4,
    bathrooms: 3,
    floors: 2,
    company: "العقارية المتحدة",
  companyLogo: "/main-page/discover/Discover1.svg",
    companyTitle: "شركة عقارية",
    isFavorite: false,
    }
];