import { PropertyCard } from "@/types/property-project-card";
export const mockProperties: PropertyCard[] = [
  {
    id: 1,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/propertyProjects/property1.png",
    price: "14,339,814",
    area: 257,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    projectsno:"12 مشروع",
    companyLogo: "/main-page/discover/Discover2.svg",
    isFavorite: false,
  },
  {
    id: 2,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "الرياض - منطقة البنوك",
    image: "/main-page/propertyProjects/property2.png",
    price: "14,339,814",
    area: 257,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    projectsno:"30 مشروع",
    companyLogo: "/main-page/discover/Discover2.svg",
    isFavorite: false,
  },
  {
    id: 3,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/propertyProjects/property3.png",
    badge: "16 × 16",
    price: "14,339,814",
    area: 257,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
   projectsno:"30 مشروع",
    companyLogo: "/main-page/discover/Discover1.svg",
    isFavorite: false,
  },
  {
    id: 4,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/propertyProjects/property4.png",
    price: "14,339,814",
    area: 257,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
    projectsno:"30 مشروع",
    companyLogo: "/main-page/discover/Discover1.svg",
    isFavorite: false,
  },
  {
    id: 5,
    title: "مشروع هاجر 50 حي الرمال",
    subtitle: "منطقة البنوك - الرياض",
    image: "/main-page/propertyProjects/property5.png",
    price: "14,339,814",
    area: 257,
    bedrooms: 5,
    bathrooms: 4,
    floors: 2,
    company: "مارفن للتطوير العقاري",
        projectsno:"20 مشروع",
    companyLogo: "/main-page/discover/Discover1.svg",
    isFavorite: false,
  },
  {
    id: 6,
    title: "مشروع الرقعة 35 حي النخيل",
    subtitle: "شرق الرياض",
    image: "/main-page/propertyProjects/property6.png",
    price: "18,500,000",
    area: 250,
    bedrooms: 4,
    bathrooms: 5,
    floors: 1,
    company: "الشركة العربية للتطوير",
        projectsno:"10 مشروع",
    companyLogo: "/main-page/discover/Discover1.svg",
    isFavorite: false,
  },
];